export default {
  SPLASH: "Splash",
  LOGIN: "Login",
  BOTTOM_TAB: "BottomTab",
  REGISTER: "Register",
  SKILLS: "Skills",
  JOB: "Job",
  REQUEST_TIME_OFF: "RequestTimeOff",

  // Bottom Tab Navigator
  HOME: "Home",
  HOMESCREEN: "HomeScreen",
  JOBS: "Jobs",
  TRAINING: "Training",
  EVENTS: "Events",
  ACCOUNT: "Account",
  PROFILE_STACK: "Profile_Stack",
  PROFILE: "Profile",
  NOTIFICATIONS_STACK: "Notifications_Stack",
  NOTIFICATIONS: "Notification",
  NOTIFICATIONS_DETAIL: "NotificationDetail",
  // Perk Stack Navigator,
  PERK: "Perk",
  PERK_DETAIL: "PerkDetail",
  // Challenges Stack Navigator
  CHALLENGES_STACK: "Challenges_Stack",
  CHALLENGES: "Challenges",
  CHALLENGE_DETAIL: "ChallengeDetail",
  EMPLOYMENT_SUMMARY: "EmploymentSummary",
  COMPENSATION_SUMMARY: "CompensationSummary",
  ASSETS_SUMMARY: "AssetsSummary",
  QUALIFICATIONS_SUMMARY: "QualificationsSummary",
  EVENTS: "Events",
  EVENT_STACK: "EventStack",
  DOCUMENTS: "Documents",
  DOCUMENT_DETAIL: "DocumentDetail",
};
