export const bands = [
    {"value": "1", "label": "Big River First Nation"},
{"value": "2", "label": "Pelican Lake First Nation"},
{"value": "3", "label": "Witchekan Lake First Nation"},
{"value": "4", "label": "Ahtahkakoop First Nation"},
{"value": "5", "label": "Moosomin First Nation"},
{"value": "6", "label": "Red Pheasant First Nation"},
{"value": "7", "label": "Sweetgrass First Nation"},
{"value": "8", "label": "Young Chippewayan First Nation"},
{"value": "9", "label": "Little Pine"},
{"value": "10", "label": "Lucky Man"},
{"value": "11", "label": "Mosquito Grizzly Bear's Head Lean Man First Nation"},
{"value": "12", "label": "Poundmaker First Nation"},
{"value": "13", "label": "Carry The Kettle First Nation"},
{"value": "14", "label": "Little Black Bear First Nation"},
{"value": "15", "label": "Muscowpetung First Nation"},
{"value": "16", "label": "Nekaneet First Nation"},
{"value": "17", "label": "Okanese First Nation"},
{"value": "18", "label": "Pasqua First Nation"},
{"value": "19", "label": "Peepeekisis First Nation"},
{"value": "20", "label": "Piapot First Nation"},
{"value": "21", "label": "Standing Buffalo First Nation"},
{"value": "22", "label": "Star Blanket First Nation"},
{"value": "23", "label": "Wood Mountain First Nation"},
{"value": "24", "label": "Birch Narrows First Nation"},
{"value": "25", "label": "Buffalo River First Nation"},
{"value": "26", "label": "Canoe Lake First Nation"},
{"value": "27", "label": "Clearwater River Dene Nation"},
{"value": "28", "label": "English River First Nation"},
{"value": "29", "label": "Flying Dust First Nation"},
{"value": "30", "label": "Island Lake First Nation"},
{"value": "31", "label": "Makwa Sahgaiehcan First Nation"},
{"value": "32", "label": "Waterhen Lake First Nation"},
{"value": "33", "label": "Black Lake Denesuline Nation"},
{"value": "34", "label": "Cumberland House Cree Nation"},
{"value": "35", "label": "Fond Du Lac Denesuline Nation"},
{"value": "36", "label": "Hatchet Lake Denesuline Nation"},
{"value": "37", "label": "James Smith First Nation"},
{"value": "38", "label": "Lac La Ronge Indian Band"},
{"value": "39", "label": "Montreal Lake Cree Nation"},
{"value": "40", "label": "Peter Ballantyne Cree Nation"},
{"value": "41", "label": "Red Earth First Nation"},
{"value": "42", "label": "Shoal Lake Cree Nation"},
{"value": "43", "label": "Sturgeon Lake First Nation"},
{"value": "44", "label": "Wahpeton Dakota First Nation"},
{"value": "45", "label": "Kinistin Saulteaux Nation"},
{"value": "46", "label": "Mistawasis First Nation"},
{"value": "47", "label": "Muskeg Lake Cree Nation"},
{"value": "48", "label": "Muskoday First Nation"},
{"value": "49", "label": "One Arrow First Nation"},
{"value": "50", "label": "Yellow Quill First Nation"},
{"value": "51", "label": "Whitecap Dakota First Nation"},
{"value": "52", "label": "Ochapowace First Nation"},
{"value": "53", "label": "White Bear First Nation"},
{"value": "54", "label": "Day Star First Nation"},
{"value": "55", "label": "George Gordon First Nation"},
{"value": "56", "label": "Kawacatoose First Nation"},
{"value": "57", "label": "Muskowekwan First Nation"},
{"value": "58", "label": "Cote First Nation"},
{"value": "59", "label": "Kahkewistahaw First Nation"},
{"value": "60", "label": "Keeseekoose First Nation"},
{"value": "61", "label": "Key First Nation"},
{"value": "62", "label": "Ocean Man First Nation"},
{"value": "63", "label": "Sakimay First Nation"},
{"value": "64", "label": "Beardy's & Okemasis First Nation"},
{"value": "65", "label": "Chacachas First Nation"},
{"value": "66", "label": "Chakastapaysin First Nation"},
{"value": "67", "label": "Cowessess First Nation"},
{"value": "68", "label": "Fishing Lake First Nation"},
{"value": "69", "label": "Onion Lake First Nation"},
{"value": "70", "label": "Peter Chapman First Nation"},
{"value": "71", "label": "Pheasant Rump Nakota First Nation"},
{"value": "72", "label": "Saulteaux First Nation"},
{"value": "73", "label": "Thunderchild First Nation"},
{"value": "74", "label": "Other"},
{"value": "75", "label": "Don't Know"},
{"value": "76", "label": "?Esdilagh First Nation"},
{"value": "77", "label": "Adams Lake"},
{"value": "78", "label": "Ahousaht"},
{"value": "79", "label": "Aitchelitz"},
{"value": "80", "label": "Alexis Creek"},
{"value": "81", "label": "Ashcroft"},
{"value": "82", "label": "Beecher Bay"},
{"value": "83", "label": "Blueberry River First Nations"},
{"value": "84", "label": "Bonaparte"},
{"value": "85", "label": "Boothroyd"},
{"value": "86", "label": "Boston Bar First Nation"},
{"value": "87", "label": "Bridge River"},
{"value": "88", "label": "Burns Lake"},
{"value": "89", "label": "Campbell River"},
{"value": "90", "label": "Canim Lake"},
{"value": "91", "label": "Cape Mudge"},
{"value": "92", "label": "Cayoose Creek"},
{"value": "93", "label": "Chawathil"},
{"value": "94", "label": "Cheam"},
{"value": "95", "label": "Cheslatta Carrier Nation"},
{"value": "96", "label": "Coldwater"},
{"value": "97", "label": "Cook's Ferry"},
{"value": "98", "label": "Cowichan"},
{"value": "99", "label": "Da'naxda'xw First Nation"},
{"value": "100", "label": "Ditidaht"},
{"value": "101", "label": "Doig River First Nation"},
{"value": "102", "label": "Douglas"},
{"value": "103", "label": "Dzawada'enuxw First Nation"},
{"value": "104", "label": "Ehattesaht"},
{"value": "105", "label": "Esk'etemc"},
{"value": "106", "label": "Esquimalt"},
{"value": "107", "label": "Fort Nelson First Nation"},
{"value": "108", "label": "Gitanmaax"},
{"value": "109", "label": "Gitanyow"},
{"value": "110", "label": "Gitga'at First Nation"},
{"value": "111", "label": "Gitsegukla"},
{"value": "112", "label": "Gitwangak"},
{"value": "113", "label": "Gitxaala Nation"},
{"value": "114", "label": "Glen Vowell"},
{"value": "115", "label": "Gwa'Sala-Nakwaxda'xw"},
{"value": "116", "label": "Gwawaenuk Tribe"},
{"value": "117", "label": "Hagwilget Village"},
{"value": "118", "label": "Haisla Nation"},
{"value": "119", "label": "Halalt"},
{"value": "120", "label": "Halfway River First Nation"},
{"value": "121", "label": "Heiltsuk"},
{"value": "122", "label": "Hesquiaht"},
{"value": "123", "label": "High Bar"},
{"value": "124", "label": "Homalco"},
{"value": "125", "label": "Hupacasath First Nation"},
{"value": "126", "label": "Huu-ay-aht First Nations"},
{"value": "127", "label": "Iskut"},
{"value": "128", "label": "K'Ã³moks First Nation"},
{"value": "129", "label": "Ka:'yu:'k't'h'/Che:k:tles7et'h' First Nations"},
{"value": "130", "label": "Kanaka Bar"},
{"value": "131", "label": "Katzie"},
{"value": "132", "label": "Kispiox"},
{"value": "133", "label": "Kitasoo"},
{"value": "134", "label": "Kitselas"},
{"value": "135", "label": "Kitsumkalum"},
{"value": "136", "label": "Klahoose First Nation"},
{"value": "137", "label": "Kwadacha"},
{"value": "138", "label": "Kwakiutl"},
{"value": "139", "label": "Kwantlen First Nation"},
{"value": "140", "label": "Kwaw-kwaw-Apilt"},
{"value": "141", "label": "Kwiakah"},
{"value": "142", "label": "Kwikwasut'inuxw Haxwa'mis"},
{"value": "143", "label": "Kwikwetlem First Nation"},
{"value": "144", "label": "Lake Babine Nation"},
{"value": "145", "label": "Lake Cowichan First Nation"},
{"value": "146", "label": "Lax Kw'alaams"},
{"value": "147", "label": "Leq' a: mel First Nation"},
{"value": "148", "label": "Lheidli T'enneh"},
{"value": "149", "label": "Lhoosk'uz Dene Nation"},
{"value": "150", "label": "Lhtako Dene Nation"},
{"value": "151", "label": "Lil'wat Nation"},
{"value": "152", "label": "Little Shuswap Lake"},
{"value": "153", "label": "Lower Kootenay"},
{"value": "154", "label": "Lower Nicola"},
{"value": "155", "label": "Lower Similkameen"},
{"value": "156", "label": "Lyackson"},
{"value": "157", "label": "Lytton"},
{"value": "158", "label": "Malahat First Nation"},
{"value": "159", "label": "Mamalilikulla-Qwe'Qwa'Sot'Em"},
{"value": "160", "label": "Matsqui"},
{"value": "161", "label": "McLeod Lake"},
{"value": "162", "label": "Metlakatla"},
{"value": "163", "label": "Moricetown"},
{"value": "164", "label": "Mowachaht/Muchalaht"},
{"value": "165", "label": "Musqueam"},
{"value": "166", "label": "N'Quatqua"},
{"value": "167", "label": "Nadleh Whuten"},
{"value": "168", "label": "Nak'azdli Whut'en"},
{"value": "169", "label": "Namgis First Nation"},
{"value": "170", "label": "Nanoose First Nation"},
{"value": "171", "label": "Nazko First Nation"},
{"value": "172", "label": "Nee-Tahi-Buhn"},
{"value": "173", "label": "Neskonlith"},
{"value": "174", "label": "New Westminster"},
{"value": "175", "label": "Nicomen"},
{"value": "176", "label": "Nisga'a Village of Gingolx"},
{"value": "177", "label": "Nisga'a Village of Gitwinksihlkw"},
{"value": "178", "label": "Nisga'a Village of Laxgalt'sap"},
{"value": "179", "label": "Nisga'a Village of New Aiyansh"},
{"value": "180", "label": "Nooaitch"},
{"value": "181", "label": "Nuchatlaht"},
{"value": "182", "label": "Nuxalk Nation"},
{"value": "183", "label": "Okanagan"},
{"value": "184", "label": "Old Massett Village Council"},
{"value": "185", "label": "Oregon Jack Creek"},
{"value": "186", "label": "Osoyoos"},
{"value": "187", "label": "Oweekeno/Wuikinuxv Nation"},
{"value": "188", "label": "Pacheedaht First Nation"},
{"value": "189", "label": "Pauquachin"},
{"value": "190", "label": "Penelakut Tribe"},
{"value": "191", "label": "Penticton"},
{"value": "192", "label": "Peters"},
{"value": "193", "label": "Popkum"},
{"value": "194", "label": "Prophet River First Nation"},
{"value": "195", "label": "Qualicum First Nation"},
{"value": "196", "label": "Quatsino"},
{"value": "197", "label": "Saik'uz First Nation"},
{"value": "198", "label": "Samahquam"},
{"value": "199", "label": "Saulteau First Nations"},
{"value": "200", "label": "Scowlitz"},
{"value": "201", "label": "Seabird Island"},
{"value": "202", "label": "Sechelt"},
{"value": "203", "label": "Semiahmoo"},
{"value": "204", "label": "Seton Lake"},
{"value": "205", "label": "Shackan"},
{"value": "206", "label": "Shuswap"},
{"value": "207", "label": "Shxw'ow'hamel First Nation"},
{"value": "208", "label": "ShxwhÃ¡:y Village"},
{"value": "209", "label": "Simpcw First Nation"},
{"value": "210", "label": "Siska"},
{"value": "211", "label": "Skatin Nations"},
{"value": "212", "label": "Skawahlook First Nation"},
{"value": "213", "label": "Skeetchestn"},
{"value": "214", "label": "Skidegate"},
{"value": "215", "label": "Skin Tyee"},
{"value": "216", "label": "Skowkale"},
{"value": "217", "label": "Skuppah"},
{"value": "218", "label": "Skwah"},
{"value": "219", "label": "Sliammon"},
{"value": "220", "label": "Snuneymuxw First Nation"},
{"value": "221", "label": "Soda Creek"},
{"value": "222", "label": "Songhees First Nation"},
{"value": "223", "label": "Soowahlie"},
{"value": "224", "label": "Splatsin"},
{"value": "225", "label": "Spuzzum"},
{"value": "226", "label": "Squamish"},
{"value": "227", "label": "Squiala First Nation"},
{"value": "228", "label": "St. Mary's"},
{"value": "229", "label": "Stellat'en First Nation"},
{"value": "230", "label": "Sts'ailes"},
{"value": "231", "label": "Stswecem'c Xgat'tem First Nation"},
{"value": "232", "label": "Stz'uminus First Nation"},
{"value": "233", "label": "Sumas First Nation"},
{"value": "234", "label": "T'Sou-ke First Nation"},
{"value": "235", "label": "T'it'q'et"},
{"value": "236", "label": "Tahltan"},
{"value": "237", "label": "Takla Lake First Nation"},
{"value": "238", "label": "Tk'emlÃºps te SecwÃ©pemc"},
{"value": "239", "label": "Tl'azt'en Nation"},
{"value": "240", "label": "Tl'etinqox Government"},
{"value": "241", "label": "Tla-o-qui-aht First Nations"},
{"value": "242", "label": "Tlatlasikwala"},
{"value": "243", "label": "Tlowitsis Tribe"},
{"value": "244", "label": "Tobacco Plains"},
{"value": "245", "label": "Toosey"},
{"value": "246", "label": "Toquaht"},
{"value": "247", "label": "Ts'kw'aylaxw First Nation"},
{"value": "248", "label": "Tsartlip"},
{"value": "249", "label": "Tsawout First Nation"},
{"value": "250", "label": "Tsawwassen First Nation"},
{"value": "251", "label": "Tsay Keh Dene"},
{"value": "252", "label": "Tseshaht"},
{"value": "253", "label": "Tseycum"},
{"value": "254", "label": "Tsleil-Waututh Nation"},
{"value": "255", "label": "Tzeachten"},
{"value": "256", "label": "Uchucklesaht"},
{"value": "257", "label": "Ucluelet First Nation"},
{"value": "258", "label": "Ulkatcho"},
{"value": "259", "label": "Union Bar"},
{"value": "260", "label": "Upper Nicola"},
{"value": "261", "label": "Upper Similkameen"},
{"value": "262", "label": "West Moberly First Nations"},
{"value": "263", "label": "Westbank First Nation"},
{"value": "264", "label": "Wet'suwet'en First Nation"},
{"value": "265", "label": "Whispering Pines/Clinton"},
{"value": "266", "label": "Williams Lake"},
{"value": "267", "label": "Xaxli'p"},
{"value": "268", "label": "Xeni Gwet'in First Nations Government"},
{"value": "269", "label": "Yakweakwioose"},
{"value": "270", "label": "Yale First Nation"},
{"value": "271", "label": "Yekooche First Nation"},
{"value": "272", "label": "Yunesit'in Government"},
{"value": "273", "label": "?Akisq'nuk First Nation"},
{"value": "274", "label": "Alexander"},
{"value": "275", "label": "Alexis Nakota Sioux Nation"},
{"value": "276", "label": "Athabasca Chipewyan First Nation"},
{"value": "277", "label": "Bearspaw"},
{"value": "278", "label": "Beaver First Nation"},
{"value": "279", "label": "Beaver Lake Cree Nation"},
{"value": "280", "label": "Bigstone Cree Nation"},
{"value": "281", "label": "Blood"},
{"value": "282", "label": "Chiniki"},
{"value": "283", "label": "Chipewyan Prairie First Nation"},
{"value": "284", "label": "Cold Lake First Nations"},
{"value": "285", "label": "Dene Tha'"},
{"value": "286", "label": "Driftpile First Nation"},
{"value": "287", "label": "Duncan's First Nation"},
{"value": "288", "label": "Enoch Cree Nation #440"},
{"value": "289", "label": "Ermineskin Tribe"},
{"value": "290", "label": "Fort McKay First Nation"},
{"value": "291", "label": "Fort McMurray #468 First Nation"},
{"value": "292", "label": "Frog Lake"},
{"value": "293", "label": "Heart Lake"},
{"value": "294", "label": "Horse Lake First Nation"},
{"value": "295", "label": "Kapawe'no First Nation"},
{"value": "296", "label": "Kehewin Cree Nation"},
{"value": "297", "label": "Little Red River Cree Nation"},
{"value": "298", "label": "Loon River Cree"},
{"value": "299", "label": "Louis Bull"},
{"value": "300", "label": "Lubicon Lake"},
{"value": "301", "label": "Mikisew Cree First Nation"},
{"value": "302", "label": "Montana"},
{"value": "303", "label": "O'Chiese"},
{"value": "304", "label": "Paul"},
{"value": "305", "label": "Peerless Trout First Nation"},
{"value": "306", "label": "Piikani Nation"},
{"value": "307", "label": "Saddle Lake Cree Nation"},
{"value": "308", "label": "Samson"},
{"value": "309", "label": "Sawridge First Nation"},
{"value": "310", "label": "Siksika Nation"},
{"value": "311", "label": "Smith's Landing First Nation"},
{"value": "312", "label": "Stoney"},
{"value": "313", "label": "Sturgeon Lake First Nation"},
{"value": "314", "label": "Sucker Creek"},
{"value": "315", "label": "Sunchild First Nation"},
{"value": "316", "label": "Swan River First Nation"},
{"value": "317", "label": "Tallcree"},
{"value": "318", "label": "Tsuu T'ina Nation"},
{"value": "319", "label": "Wesley"},
{"value": "320", "label": "Whitefish Lake"},
{"value": "321", "label": "Woodland Cree First Nation"},
{"value": "322", "label": "Barren Lands"},
{"value": "323", "label": "Berens River"},
{"value": "324", "label": "Birdtail Sioux"},
{"value": "325", "label": "Black River First Nation"},
{"value": "326", "label": "Bloodvein"},
{"value": "327", "label": "Brokenhead Ojibway Nation"},
{"value": "328", "label": "Buffalo Point First Nation"},
{"value": "329", "label": "Bunibonibee Cree Nation"},
{"value": "330", "label": "Canupawakpa Dakota First Nation"},
{"value": "331", "label": "Chemawawin Cree Nation"},
{"value": "332", "label": "Cross Lake Band of Indians"},
{"value": "333", "label": "Dakota Plains"},
{"value": "334", "label": "Dakota Tipi"},
{"value": "335", "label": "Dauphin River"},
{"value": "336", "label": "Ebb and Flow"},
{"value": "337", "label": "Fisher River"},
{"value": "338", "label": "Fort Alexander"},
{"value": "339", "label": "Fox Lake"},
{"value": "340", "label": "Gamblers"},
{"value": "341", "label": "Garden Hill First Nations"},
{"value": "342", "label": "God's Lake First Nation"},
{"value": "343", "label": "Hollow Water"},
{"value": "344", "label": "Keeseekoowenin"},
{"value": "345", "label": "Kinonjeoshtegon First Nation"},
{"value": "346", "label": "Lake Manitoba"},
{"value": "347", "label": "Lake St. Martin"},
{"value": "348", "label": "Little Grand Rapids"},
{"value": "349", "label": "Little Saskatchewan"},
{"value": "350", "label": "Long Plain"},
{"value": "351", "label": "Manto Sipi Cree Nation"},
{"value": "352", "label": "Marcel Colomb First Nation"},
{"value": "353", "label": "Mathias Colomb"},
{"value": "354", "label": "Misipawistik Cree Nation"},
{"value": "355", "label": "Mosakahiken Cree Nation"},
{"value": "356", "label": "Nisichawayasihk Cree Nation"},
{"value": "357", "label": "Northlands"},
{"value": "358", "label": "Norway House Cree Nation"},
{"value": "359", "label": "O-Chi-Chak-Ko-Sipi First Nation"},
{"value": "360", "label": "O-Pipon-Na-Piwin Cree Nation"},
{"value": "361", "label": "Opaskwayak Cree Nation"},
{"value": "362", "label": "Pauingassi First Nation"},
{"value": "363", "label": "Peguis"},
{"value": "364", "label": "Pinaymootang First Nation"},
{"value": "365", "label": "Pine Creek"},
{"value": "366", "label": "Poplar River First Nation"},
{"value": "367", "label": "Red Sucker Lake"},
{"value": "368", "label": "Rolling River"},
{"value": "369", "label": "Roseau River Anishinabe First Nation Government"},
{"value": "370", "label": "Sandy Bay"},
{"value": "371", "label": "Sapotaweyak Cree Nation"},
{"value": "372", "label": "Sayisi Dene First Nation"},
{"value": "373", "label": "Shamattawa First Nation"},
{"value": "374", "label": "Sioux Valley Dakota Nation"},
{"value": "375", "label": "Skownan First Nation"},
{"value": "376", "label": "St. Theresa Point"},
{"value": "377", "label": "Swan Lake"},
{"value": "378", "label": "Tataskweyak Cree Nation"},
{"value": "379", "label": "Tootinaowaziibeeng Treaty Reserve"},
{"value": "380", "label": "War Lake First Nation"},
{"value": "381", "label": "Wasagamack First Nation"},
{"value": "382", "label": "Waywayseecappo First Nation Treaty Four - 1874"},
{"value": "383", "label": "Wuskwi Sipihk First Nation"},
{"value": "384", "label": "York Factory First Nation"},
{"value": "385", "label": "Aamjiwnaang"},
{"value": "386", "label": "Albany"},
{"value": "387", "label": "Alderville First Nation"},
{"value": "388", "label": "Algonquins of Pikwakanagan First Nation"},
{"value": "389", "label": "Animbiigoo Zaagi'igan Anishinaabek"},
{"value": "390", "label": "Anishinabe of Wauzhushk Onigum"},
{"value": "391", "label": "Anishnaabeg of Naongashiing"},
{"value": "392", "label": "Aroland"},
{"value": "393", "label": "Atikameksheng Anishnawbek"},
{"value": "394", "label": "Attawapiskat"},
{"value": "395", "label": "Aundeck-Omni-Kaning"},
{"value": "396", "label": "Batchewana First Nation"},
{"value": "397", "label": "Bay of Quinte Mohawk"},
{"value": "398", "label": "Bearfoot Onondaga"},
{"value": "399", "label": "Bearskin Lake"},
{"value": "400", "label": "Beausoleil"},
{"value": "401", "label": "Big Grassy"},
{"value": "402", "label": "Biinjitiwaabik Zaaging Anishinaabek"},
{"value": "403", "label": "Bingwi Neyaashi Anishinaabek"},
{"value": "404", "label": "Brunswick House"},
{"value": "405", "label": "Caldwell"},
{"value": "406", "label": "Cat Lake"},
{"value": "407", "label": "Chapleau Cree First Nation"},
{"value": "408", "label": "Chapleau Ojibway"},
{"value": "409", "label": "Chippewas of Georgina Island"},
{"value": "410", "label": "Chippewas of Kettle and Stony Point"},
{"value": "411", "label": "Chippewas of Nawash First Nation"},
{"value": "412", "label": "Chippewas of Rama First Nation"},
{"value": "413", "label": "Chippewas of the Thames First Nation"},
{"value": "414", "label": "Constance Lake"},
{"value": "415", "label": "Couchiching First Nation"},
{"value": "416", "label": "Curve Lake"},
{"value": "417", "label": "Deer Lake"},
{"value": "418", "label": "Delaware"},
{"value": "419", "label": "Dokis"},
{"value": "420", "label": "Eabametoong First Nation"},
{"value": "421", "label": "Eagle Lake"},
{"value": "422", "label": "Flying Post"},
{"value": "423", "label": "Fort Severn"},
{"value": "424", "label": "Fort William"},
{"value": "425", "label": "Garden River First Nation"},
{"value": "426", "label": "Ginoogaming First Nation"},
{"value": "427", "label": "Grassy Narrows First Nation"},
{"value": "428", "label": "Gull Bay"},
{"value": "429", "label": "Henvey Inlet First Nation"},
{"value": "430", "label": "Hiawatha First Nation"},
{"value": "431", "label": "Iskatewizaagegan #39 Independent First Nation"},
{"value": "432", "label": "Kasabonika Lake"},
{"value": "433", "label": "Kee-Way-Win"},
{"value": "434", "label": "Kingfisher"},
{"value": "435", "label": "Kitchenuhmaykoosib Inninuwug"},
{"value": "436", "label": "Konadaha Seneca"},
{"value": "437", "label": "Lac Des Mille Lacs"},
{"value": "438", "label": "Lac La Croix"},
{"value": "439", "label": "Lac Seul"},
{"value": "440", "label": "Long Lake No.58 First Nation"},
{"value": "441", "label": "Lower Cayuga"},
{"value": "442", "label": "Lower Mohawk"},
{"value": "443", "label": "M'Chigeeng First Nation"},
{"value": "444", "label": "Magnetawan"},
{"value": "445", "label": "Martin Falls"},
{"value": "446", "label": "Matachewan"},
{"value": "447", "label": "Mattagami"},
{"value": "448", "label": "McDowell Lake"},
{"value": "449", "label": "Michipicoten"},
{"value": "450", "label": "Mishkeegogamang"},
{"value": "451", "label": "Missanabie Cree"},
{"value": "452", "label": "Mississauga"},
{"value": "453", "label": "Mississauga's of Scugog Island First Nation"},
{"value": "454", "label": "Mississaugas of the Credit"},
{"value": "455", "label": "Mitaanjigamiing First Nation"},
{"value": "456", "label": "Mohawks of Akwesasne"},
{"value": "457", "label": "Mohawks of the Bay of Quinte"},
{"value": "458", "label": "Moose Cree First Nation"},
{"value": "459", "label": "Moose Deer Point"},
{"value": "460", "label": "Moravian of the Thames"},
{"value": "461", "label": "Munsee-Delaware Nation"},
{"value": "462", "label": "Muskrat Dam Lake"},
{"value": "463", "label": "Naicatchewenin"},
{"value": "464", "label": "Naotkamegwanning"},
{"value": "465", "label": "Neskantaga First Nation"},
{"value": "466", "label": "Nibinamik First Nation"},
{"value": "467", "label": "Nigigoonsiminikaaning First Nation"},
{"value": "468", "label": "Niharondasa Seneca"},
{"value": "469", "label": "Nipissing First Nation"},
{"value": "470", "label": "North Caribou Lake"},
{"value": "471", "label": "North Spirit Lake"},
{"value": "472", "label": "Northwest Angle No.33"},
{"value": "473", "label": "Northwest Angle No.37"},
{"value": "474", "label": "Obashkaandagaang"},
{"value": "475", "label": "Ochiichagwe'babigo'ining First Nation"},
{"value": "476", "label": "Ojibway Nation of Saugeen"},
{"value": "477", "label": "Ojibways of Onigaming First Nation"},
{"value": "478", "label": "Ojibways of the Pic River First Nation"},
{"value": "479", "label": "Oneida"},
{"value": "480", "label": "Oneida Nation of the Thames"},
{"value": "481", "label": "Onondaga Clear Sky"},
{"value": "482", "label": "Pays Plat"},
{"value": "483", "label": "Pic Mobert"},
{"value": "484", "label": "Pikangikum"},
{"value": "485", "label": "Poplar Hill"},
{"value": "486", "label": "Rainy River First Nations"},
{"value": "487", "label": "Red Rock"},
{"value": "488", "label": "Sachigo Lake"},
{"value": "489", "label": "Sagamok Anishnawbek"},
{"value": "490", "label": "Sandy Lake"},
{"value": "491", "label": "Saugeen"},
{"value": "492", "label": "Seine River First Nation"},
{"value": "493", "label": "Serpent River"},
{"value": "494", "label": "Shawanaga First Nation"},
{"value": "495", "label": "Sheguiandah"},
{"value": "496", "label": "Sheshegwaning"},
{"value": "497", "label": "Shoal Lake No.40"},
{"value": "498", "label": "Six Nations of the Grand River"},
{"value": "499", "label": "Slate Falls Nation"},
{"value": "500", "label": "Taykwa Tagamou Nation"},
{"value": "501", "label": "Temagami First Nation"},
{"value": "502", "label": "Thessalon"},
{"value": "503", "label": "Tuscarora"},
{"value": "504", "label": "Upper Cayuga"},
{"value": "505", "label": "Upper Mohawk"},
{"value": "506", "label": "Wabaseemoong Independent Nations"},
{"value": "507", "label": "Wabauskang First Nation"},
{"value": "508", "label": "Wabigoon Lake Ojibway Nation"},
{"value": "509", "label": "Wahgoshig"},
{"value": "510", "label": "Wahnapitae"},
{"value": "511", "label": "Wahta Mohawk"},
{"value": "512", "label": "Walker Mohawk"},
{"value": "513", "label": "Walpole Island"},
{"value": "514", "label": "Wapekeka"},
{"value": "515", "label": "Wasauksing First Nation"},
{"value": "516", "label": "Wawakapewin"},
{"value": "517", "label": "Webequie"},
{"value": "518", "label": "Weenusk"},
{"value": "519", "label": "Whitefish River"},
{"value": "520", "label": "Whitesand"},
{"value": "521", "label": "Wikwemikong"},
{"value": "522", "label": "Wunnumin"},
{"value": "523", "label": "Zhiibaahaasing First Nation"},
{"value": "524", "label": "Algonquins of Barriere Lake"},
{"value": "525", "label": "Atikamekw d'Opitciwan"},
{"value": "526", "label": "Bande des Innus de Pessamit"},
{"value": "527", "label": "CommunautÃ© anicinape de Kitcisakik"},
{"value": "528", "label": "Conseil de la PremiÃ¨re Nation Abitibiwinni"},
{"value": "529", "label": "Conseil des Atikamekw de Wemotaci"},
{"value": "530", "label": "Cree Nation of Chisasibi"},
{"value": "531", "label": "Cree Nation of Mistissini"},
{"value": "532", "label": "Cree Nation of Nemaska"},
{"value": "533", "label": "Cree Nation of Wemindji"},
{"value": "534", "label": "Eagle Village First Nation - Kipawa"},
{"value": "535", "label": "Eastmain"},
{"value": "536", "label": "Innu Takuaikan Uashat Mak Mani-Utenam"},
{"value": "537", "label": "Innue Essipit"},
{"value": "538", "label": "Kitigan Zibi Anishinabeg"},
{"value": "539", "label": "La Nation Innu Matimekush-Lac John"},
{"value": "540", "label": "La Nation Micmac de Gespeg"},
{"value": "541", "label": "Les Atikamekw de Manawan"},
{"value": "542", "label": "Les Innus de Ekuanitshit"},
{"value": "543", "label": "Listuguj Mi'gmaq Government"},
{"value": "544", "label": "Long Point First Nation"},
{"value": "545", "label": "Micmacs of Gesgapegiag"},
{"value": "546", "label": "Mohawks of KahnawÃ¡:ke"},
{"value": "547", "label": "Mohawks of Kanesatake"},
{"value": "548", "label": "Montagnais de Natashquan"},
{"value": "549", "label": "Montagnais de Pakua Shipi"},
{"value": "550", "label": "Montagnais de Unamen Shipu"},
{"value": "551", "label": "Montagnais du Lac St-Jean"},
{"value": "552", "label": "Naskapi Nation of Kawawachikamach"},
{"value": "553", "label": "Nation Anishnabe du Lac Simon"},
{"value": "554", "label": "Nation Huronne Wendat"},
{"value": "555", "label": "Odanak"},
{"value": "556", "label": "OujÃ©-Bougoumou Cree Nation"},
{"value": "557", "label": "PremiÃ¨re Nation Malecite de Viger"},
{"value": "558", "label": "PremiÃ¨re Nation des AbÃ©nakis de WÃ´linak"},
{"value": "559", "label": "PremiÃ¨re nation de Whapmagoostui"},
{"value": "560", "label": "The Crees of the Waskaganish First Nation"},
{"value": "561", "label": "Timiskaming First Nation"},
{"value": "562", "label": "Waswanipi"},
{"value": "563", "label": "Wolf Lake"},
{"value": "564", "label": "Buctouche"},
{"value": "565", "label": "Eel Ground"},
{"value": "566", "label": "Eel River Bar First Nation"},
{"value": "567", "label": "Elsipogtog First Nation"},
{"value": "568", "label": "Esgenoopetitj First Nation"},
{"value": "569", "label": "Fort Folly"},
{"value": "570", "label": "Indian Island"},
{"value": "571", "label": "Kingsclear"},
{"value": "572", "label": "Madawaska Maliseet First Nation"},
{"value": "573", "label": "Metepenagiag Mi'kmaq Nation"},
{"value": "574", "label": "Oromocto"},
{"value": "575", "label": "Pabineau"},
{"value": "576", "label": "Saint Mary's"},
{"value": "577", "label": "Tobique"},
{"value": "578", "label": "Woodstock"},
{"value": "579", "label": "Acadia"},
{"value": "580", "label": "Annapolis Valley"},
{"value": "581", "label": "Bear River"},
{"value": "582", "label": "Eskasoni"},
{"value": "583", "label": "Glooscap First Nation"},
{"value": "584", "label": "Membertou"},
{"value": "585", "label": "Millbrook"},
{"value": "586", "label": "Paqtnkek Mi'kmaw Nation"},
{"value": "587", "label": "Pictou Landing"},
{"value": "588", "label": "Potlotek First Nation"},
{"value": "589", "label": "SIPEKNE'KATIK"},
{"value": "590", "label": "Wagmatcook"},
{"value": "591", "label": "Waycobah First Nation"},
{"value": "592", "label": "Abegweit"},
{"value": "593", "label": "Lennox Island"},
{"value": "594", "label": "Miawpukek"},
{"value": "595", "label": "Mushuau Innu First Nation"},
{"value": "596", "label": "Qalipu Mi'kmaq First Nation"},
{"value": "597", "label": "Sheshatshiu Innu First Nation"},
{"value": "598", "label": "Acho Dene Koe First Nation"},
{"value": "599", "label": "Aklavik"},
{"value": "600", "label": "Behdzi Ahda First Nation"},
{"value": "601", "label": "Dechi Laot'i First Nations"},
{"value": "602", "label": "Deh GÃ¡h Got'ie Dene First Nation"},
{"value": "603", "label": "Deline First Nation"},
{"value": "604", "label": "Deninu K'ue First Nation"},
{"value": "605", "label": "Dog Rib Rae"},
{"value": "606", "label": "Fort Good Hope"},
{"value": "607", "label": "Gameti First Nation"},
{"value": "608", "label": "Gwichya Gwich'in"},
{"value": "609", "label": "Inuvik Native"},
{"value": "610", "label": "Jean Marie River First Nation"},
{"value": "611", "label": "K'atlodeeche First Nation"},
{"value": "612", "label": "Ka'a'gee Tu First Nation"},
{"value": "613", "label": "Liidlii Kue First Nation"},
{"value": "614", "label": "Lutsel K'e Dene First Nation"},
{"value": "615", "label": "Nahanni Butte"},
{"value": "616", "label": "Pehdzeh Ki First Nation"},
{"value": "617", "label": "Salt River First Nation #195"},
{"value": "618", "label": "Sambaa K'e (Trout Lake) Dene"},
{"value": "619", "label": "Tetlit Gwich'in"},
{"value": "620", "label": "Tulita Dene"},
{"value": "621", "label": "West Point First Nation"},
{"value": "622", "label": "Wha Ti First Nation"},
{"value": "623", "label": "Yellowknives Dene First Nation"},
{"value": "624", "label": "Aishihik"},
{"value": "625", "label": "Carcross/Tagish First Nation"},
{"value": "626", "label": "Champagne"},
{"value": "627", "label": "Champagne and Aishihik First Nations"},
{"value": "628", "label": "Dease River"},
{"value": "629", "label": "First Nation of Nacho Nyak Dun"},
{"value": "630", "label": "Kluane First Nation"},
{"value": "631", "label": "Kwanlin Dun First Nation"},
{"value": "632", "label": "Liard First Nation"},
{"value": "633", "label": "Little Salmon/Carmacks First Nation"},
{"value": "634", "label": "Ross River"},
{"value": "635", "label": "Selkirk First Nation"},
{"value": "636", "label": "Ta'an Kwach'an"},
{"value": "637", "label": "Taku River Tlingit"},
{"value": "638", "label": "Teslin Tlingit Council"},
{"value": "639", "label": "Tr'ondÃ«k HwÃ«ch'in"},
{"value": "640", "label": "Vuntut Gwitchin First Nation"},
{"value": "641", "label": "White River First Nation"},
{"value": "642", "label": "Big Island Lake Cree Nation"},
{"value": "643", "label": "EXPORTDATA"},
{"value": "644", "label": "Southend"},
{"value": "645", "label": "Pelican Narrows"},
{"value": "646", "label": "Deschambault Lake"},
{"value": "647", "label": "Sandy Bay"},
{"value": "648", "label": "Sturgeon Landing"},
{"value": "649", "label": "Denare Beach"},
{"value": "650", "label": "Camsell Portage"},
{"value": "651", "label": "Uranium City "},
{"value": "652", "label": "Wollaston Lake"},
{"value": "653", "label": "Stony Rapids"},
{"value": "654", "label": "Demo Nation"},
]