export const didYouKnow = [
  {
    percentage:
      "perks.virtual_primary_care.details.did_you_know_review.0.percentage",
    description:
      "perks.virtual_primary_care.details.did_you_know_review.0.desc",
  },
  {
    percentage:
      "perks.virtual_primary_care.details.did_you_know_review.1.percentage",
    description:
      "perks.virtual_primary_care.details.did_you_know_review.1.desc",
  },
  {
    percentage:
      "perks.virtual_primary_care.details.did_you_know_review.2.percentage",
    description:
      "perks.virtual_primary_care.details.did_you_know_review.2.desc",
  },
];
export const savingBulletPoints = [
  {
    title: "Cost Savings",
    list: [
      "$0 (or low dollar) visit fee",
      "Access to third-party prescription discount card",
      "Intelligent referrals",
    ],
  },
  {
    title: "Convenience",
    list: [
      "Care on your schedule",
      "VPC visits within 72 hours",
      "24/7 virtual urgent care",
    ],
  },
  {
    title: "Connection",
    list: [
      "See the same virtual PCP",
      "Dedicated care navigation team",
      "On-demand chat—24/7",
    ],
  },
  {
    title: "Access",
    list: [
      "Continuity of care",
      "Ongoing chronic care management",
      "Lab work & imaging",
    ],
  },
];
export const primaryCare = "perks.virtual_primary_care.details.walmart_table";
export const urgentCare = [
  "Abrasions",
  "Acne",
  "Allergies",
  "Asthma",
  "Bacterial Vaginosis",
  "Birth Control",
  "Bites and Stings",
  "Body Aches",
  "Bronchitis",
  "Bruises",
  "Cough",
  "OVID-19 Antibody",
  "Testing",
  "COVID-19 Screening",
  "Dehydration",
  "Diarrhea",
  "Fever",
  "Flu",
  "Frostbite",
  "Gout",
  "Headaches",
  "Hives",
  "Itchy Eyes",
  "Lice",
  "Medication Refills",
  "Migraines",
  "Mild lacerations",
  "Nasal Congestion",
  "Nausea",
  "Pink Eye",
  "Respiratory Infections",
  "Sexual Health",
  "Sinus infections",
  "Skin infections",
  "Sore throat",
  "Sprains and strains",
  "Travel medications",
  "Urinary tract infections",
  "Vomiting",
  "Yeast infections",
];
export const menHealth = [
  "Acne",
  "Cold sore",
  "Enlarged prostate",
  "Erectile dysfunction*",
  "Hair loss",
  "Jock itch",
  "Low sex drive*",
  "Performance anxiety*",
  "Premature ejaculation",
  "Prostatitis",
  "Pubic lice",
  "Smoking cessation*",
  "Sexual Health",
  "Urinary incontinence",
  "Warts",
];
export const womenHealth = [
  "Acne",
  "Birth control",
  "Cold sores",
  "Dyspareunia/vulvodynia",
  "Endometriosis",
  "Eyelash thinning",
  "Hair loss",
  "Hot flashes",
  "Low sex drive*",
  "Mastitis",
  "Pain during intercourse",
  "Performance anxiety*",
  "Postpartum depression*",
  "Premenstrual syndrome",
  "Pubic lice",
  "Sexual Health",
  "Smoking cessation*",
  "Urinary incontinence",
  "Urinary tract infections",
  "Vulvovaginal atrophy",
  "Warts",
];
export const talkTherapy = [
  "Abuse",
  "ADHD/ADD",
  "Anger Management",
  "Anxiety",
  "Bipolar disorder",
  "Caregiver stress",
  "Codependency",
  "Concentration",
  "Conduct disorder",
  "Cognitive behavioral therapy",
  "Depression",
  "Divorce",
  "Domestic violence",
  "Employment",
  "LGBTQ+ issues",
  "Grief/loss",
  "Insomnia",
  "Maternal health/post-partum",
  "Mood swings",
  "Men issues",
  "Obsessive-compulsive disorder",
  "Panic attacks",
  "Parenting",
  "Performance coaching",
  "PTSD",
  "Relationships",
  "Sexual abuse",
  "Sexuality",
  "Social anxiety",
  "Spirituality",
  "Stress management",
  "Trauma",
  "Women Issues",
];
export const teenTherapy = [
  "Abuse",
  "ADHD/ADD",
  "Anger management",
  "Anxiety",
  "Bipolar disorder",
  "Bullying",
  "Codependency",
  "Cognitive disorders",
  "Concentration",
  "Conduct disorder",
  "Depression",
  "Domestic violence",
  "Female issues",
  "Grief/loss",
  "LGBTQ+ issues",
  "Male issues",
  "Mood swings",
  "Obsessive-compulsive disorder",
  "Panic attacks",
  "Performance coaching",
  "Relationships",
  "Sexual abuse",
  "Sexuality",
  "Social anxiety",
  "Trauma/PTSD",
];
export const psychiatryTherapy = [
  "Abuse",
  "ADHD/ADD 1",
  "Anger management",
  "Anxiety",
  "Bipolar disorder",
  "Codependency",
  "Cognitive disorders",
  "Concentration",
  "Conduct disorder",
  "Depression",
  "Divorce",
  "Domestic violence",
  "Employment",
  "Insomnia",
  "LGBTQ+ issues",
  "Grief/loss",
  "Maternal health/post-partum",
  "Medication management",
  "Mood swings",
  "Men's issues",
  "Obsessive-compulsive disorder",
  "Panic attacks",
  "Parenting",
  "Performance coaching",
  "Relationships",
  "Sexual abuse",
  "Sexuality",
  "Social anxiety",
  "Stress management",
  "Trauma/PTSD",
  "Women's issues",
];
export const PERKS_ROUTES = {
  VIRTUAL_PRIMARY_CARE: "VirtualPrimaryCare",
  EMPLOYEE_WELLNESS: "EmployeeWellness",
  PERCEPTION_SAVINGS: "PrescriptionSavings",
  AUTO_HOME_INSURANCE: "AutoHomeInsurance",
  ID_THEFT: "IdTheft",
  INTEREST_FREE_CREDIT_LINE: "InterestFreeCreditLine",
  FINANCIAL_LITERACY: "FinancialLiteracy",
  VOLUNTARY_BENEFITS: "VoluntaryBenefits",
  BENEFITS_DISCOUNTS: "BenefitsDiscounts",
};
